#!/bin/bash

set -e

PLATFORM=${PLATFORM:=et_genesys264}  # works fine
IMAGE_DIR=$(realpath ./build-$PLATFORM/buildroot.build/images)
IMAGE_NAME=debian-$PLATFORM.sd.img
SD_SIZE=500
SD_BOOT_SIZE=64
SD_SWAP_SIZE=

mount -l | grep `pwd`/ | while IFS=' ' read -ra LINE ; do
  sudo umount ${LINE[0]}
done
sudo losetup -a | grep `pwd`/ | while IFS=':' read -ra LINE ; do
  sudo losetup -d ${LINE[0]}
done
sudo losetup -a | grep `pwd`/ | while IFS=':' read -ra LINE ; do
  echo "Cannot detach ${LINE[*]}"
  exit 1
done

echo $SD_SIZE
rm -f $IMAGE_DIR/$IMAGE_NAME
dd if=/dev/zero of=$IMAGE_DIR/$IMAGE_NAME bs=1M count=$SD_SIZE

SD_LOOP=$(sudo losetup --find --partscan --show $IMAGE_DIR/$IMAGE_NAME)
echo "SD image device: ${SD_LOOP}"

sudo sfdisk ${SD_LOOP} <<-__EOF__
1M,${SD_BOOT_SIZE}M,0xE,*
,,,-
__EOF__

sudo partprobe ${SD_LOOP}

UUID=68d82fa1-1bb5-435f-a5e3-862176586eec
sudo mkfs.vfat -F 16 -n BOOT ${SD_LOOP}p1
sudo mkfs.ext2 -E nodiscard -L rootfs -U $UUID ${SD_LOOP}p2

mkdir -p mnt/boot
mkdir -p mnt/rootfs
mkdir -p mnt/ext2

sudo mount ${SD_LOOP}p1 ./mnt/boot
sudo mount ${SD_LOOP}p2 ./mnt/rootfs
sudo mount -t ext2 $IMAGE_DIR/rootfs.ext2 ./mnt/ext2


pushd mnt/rootfs
sudo tar xf $IMAGE_DIR/rootfs.tar
popd

# TO-DO Add build cert creation as part of making sd image
pushd mnt/boot
sudo cp $IMAGE_DIR/fw_payload.elf ./boot.elf

popd
umount_with_retry() {
    local device=$1
    local max_attempts=3
    local attempt=1

    while [ $attempt -le $max_attempts ]; do
        sudo umount -l $device
        if ! mount | grep -q $device; then
            echo "$device successfully unmounted."
            return 0
        else
            echo "Unmount attempt $attempt for $device failed. Retrying in 1 second..."
            sleep 1
            attempt=$((attempt + 1))
        fi
    done

    echo "Failed to unmount $device after $max_attempts attempts."
    return 1
}

# Unmount partitions
umount_with_retry ${SD_LOOP}p1 || exit 1
umount_with_retry ${SD_LOOP}p2 || exit 1


sudo fsck -f -p -T ${SD_LOOP}p1 || true
sudo fsck -f -p -T ${SD_LOOP}p2

sudo losetup -d ${SD_LOOP}

